<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movimiento extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'movimientos_compra',
            'modificar_fechas_compras',
            'compras',
            'crear_compras',
            'recuperar_compras',
            'consultar_compras',
            'cancelar_compras',
            'borrar_compras',
            'lista_compras_cancelar',
            'aceptar_rechazar_cancelaciones',
            'movimientos_vtas',
            'modificar_precios_compra',
            'elegir_precio',
            'modificar_fecha_vtas',
            'imprimir_vtas_canceladas',
            'modificar_folio_vtas',
            'ver_vtas',
            'ver_cxc',
            'cambiar_vendedor',
            'modif_porc_comision',
            'modif_vendedor',
            'vender_credito_cxc_vencidas',
            'registrar_productos_solicitados',
            'remisiones',
            'crear_remision',
            'recuperacion_remision',
            'consulta_remision',
            'cancelar_remision',
            'eliminar_remision',
            'facturar_remision',
            'apartados_mercancia',
            'crear_apartados',
            'consulta_apartados',
            'eliminar_apartados',
            'cargos_pagos',
            'cargos',
            'cargos_clientes',
            'borrar_cargos',
            'cargos_proveedores',
            'borrar_cargos_proveedores',
            'pagos',
            'pagos_clientes',
            'modif_pagos_clientes',
            'borrar_pagos',
            'traslado_pagos',
            'pagos_proveedores',
            'modif_pagos_proveedores',
            'borrar_pagos_proveedores',
            'traslado_pagos_proveedores',
            'notas_cargo_clientes',
            'notas_cargo_proveedores',
            'notas_credito',
            'lista_pendientes',
            'crear_notas_credito',
            'modif_fecha_notas_credito',
            'consultar_notas_credito',
            'cancelacion_notas_credito',
            'traslado_notas_credito',
            'control_devoluciones',
            'devolucion_clientes',
            'crear_devolucion',
            'crear_sin_especificar_ctes',
            'modif_fecha_dev_ctes',
            'consultar_devolucion_ctes',
            'canc_dev_ctes',
            'elim_dev_ctes',
            'devolucion_proveedores',
            'crear_dev_prov',
            'crear_sin_especificar_prov',
            'modif_fecha_dev_prov',
            'consultar_devolucion_prov',
            'canc_dev_prov',
            'elim_dev_prov',
            'gastos',
            'crear_gastos',
            'modif_fecha_gastos',
            'consulta_gastos',
            'traspasos_almacenes',
            'user_id'
    ];
}
