<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reporte extends Model
{
    use HasFactory;

    protected $fillable = [
        'administrativos',
        'reporte_por_compras',
        'reporte_de_compras',
        'reporte_ventas',
        'reporte_remisiones',
        'reporte_facturas',
        'reporte_apartados',
        'reporte_utilidad',
        'comisiones_vendedor',
        'integrados_rem_fact',
        'reporte_especial_vtas',
        'utilidad_por_vendedor',
        'vtas_canc',
        'reporte_grafico',
        'reporte_cobranza_ctes',
        'cargos_clientes',
        'pagos_clientes',
        'estado_ctas_ctes',
        'antiguedad_saldo_ctes',
        'cxc',
        'notas_credito',
        'saldos_fecha',
        'reporte_pagos_prov',
        'cargos_prov',
        'pagos_prov',
        'estado_ctas_prov',
        'antiguedad_saldo_prov',
        'cxp',
        'saldos_fecha_prov',
        'devoluciones',
        'dev_ctes',
        'dev_prov',
        'movimiento_productos',
        'ajuste_existencias',
        'rotacion_productos',
        'traspaso_almacenes',
        'cambios_precios',
        'gastos',
        'documentos_cancelados',
        'bitacora_usuarios',
        'resumenes',
        'total_dia_remisiones',
        'movimiento_clientes',
        'listado_catalogos',
        'catalogo_clientes',
        'imprimir_cat_ctes',
        'imprimir_lista_deudores',
        'catalogo_proveedores',
        'imprimir_cat_prov',
        'imprimir_lista_acreedores',
        'reporte_productos',
        'lista_precios',
        'reporte_existencias',
        'mercancia_surtir',
        'costeo_inventario',
        'existencia_anterior',
        'catalogo_vendedores',
        'reportes_estadisticos',
        'acum_vtas_ctes',
        'acum_compras_prov',
        'mov_prod',
        'kard_prod',
        'acum_utilidad',
        'rep_financiero',
        'rep_amarre_costo_promedio',
        'rep_prod_solicitados',
        'concentrados',
        'concentrado_existencias',
        'concentrado_vtas',
        'antig_saldos_ctes',
        'user_id'
    ];
}
